# Generated by Django 3.2.5 on 2021-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontacts', '0002_auto_20210909_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='label',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='contactinfolocalization',
            name='label',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='contactinfolocalization',
            name='value',
            field=models.CharField(max_length=160),
        ),
    ]
