# Generated by Django 3.2.5 on 2021-11-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontacts', '0004_auto_20211103_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='info_type',
            field=models.CharField(choices=[('email', 'Email'), ('hours', 'Hours'), ('location', 'Location'), ('phone', 'Phone'), ('website', 'Website'), ('other', 'Other')], max_length=15),
        ),
    ]
