# Generated by Django 3.1.4 on 2021-01-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmenus', '0002_auto_20210114_1439'),
        ('cmsmenus', '0002_auto_20201209_2301'),
    ]

    operations = [
    ]
