# Generated by Django 3.1.6 on 2021-03-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmenus', '0003_auto_20210119_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbaritem',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_menu', to='cmsmenus.navigationbar'),
            preserve_default=False,
        ),
    ]
