# Generated by Django 3.1.6 on 2021-05-05 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmenus', '0004_auto_20210312_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationbaritemlocalization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigationbaritemlocalization',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigationbaritemlocalization',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
