# Generated by Django 3.1.6 on 2021-05-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmspublications', '0014_auto_20210507_1618'),
        ('cmscontexts', '0007_auto_20210507_1618'),
        ('cmsmenus', '0005_auto_20210505_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigationbar_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navigationbar',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigationbar_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigationbaritem_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='inherited_content',
            field=models.ForeignKey(blank=True, help_text='Takes additional contents from a publication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inherited_content', to='cmspublications.publication'),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigationbaritem_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pub', to='cmspublications.publication'),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='webpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_page', to='cmscontexts.webpath'),
        ),
        migrations.AlterField(
            model_name='navigationbaritemlocalization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigationbaritemlocalization_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navigationbaritemlocalization',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigationbaritemlocalization_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
