# Generated by Django 3.2.3 on 2021-05-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmenus', '0006_auto_20210507_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbar',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
