# Generated by Django 3.2.3 on 2021-06-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmenus', '0007_alter_navigationbar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbaritem',
            name='url',
            field=models.TextField(blank=True, default='', help_text='url'),
        ),
    ]
