# Generated by Django 3.2.5 on 2021-12-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmenus', '0009_alter_navigationbaritem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbaritemlocalization',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
