# Generated by Django 3.2.19 on 2023-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmenus', '0011_auto_20211229_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbaritemlocalization',
            name='language',
            field=models.CharField(choices=[('', '-')], default='en', max_length=12),
        ),
    ]
