# Generated by Django 4.2.9 on 2025-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmsmenus", "0013_alter_navigationbar_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationbaritemlocalization",
            name="url",
            field=models.CharField(
                blank=True, default="", help_text="url", max_length=2048
            ),
        ),
    ]
