# Generated by Django 5.1.7 on 2026-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmenus', '0014_navigationbaritemlocalization_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navigationbaritemlocalization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
