# Generated by Django 3.1.4 on 2021-01-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0002_auto_20210115_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='state',
        ),
    ]
