# Generated by Django 3.1.4 on 2021-01-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0003_auto_20210118_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcontext',
            name='date_end',
            field=models.DateTimeField(default='2021-12-31T15:39:04.622Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationcontext',
            name='date_start',
            field=models.DateTimeField(default='2020-01-01T15:39:04.622Z'),
            preserve_default=False,
        ),
    ]
