# Generated by Django 3.1.4 on 2021-01-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0005_auto_20210118_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_publication', to='cmspublications.publication')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_publication', to='cmspublications.publication')),
            ],
            options={
                'verbose_name_plural': 'Related Publications',
                'unique_together': {('publication', 'related')},
            },
        ),
        migrations.DeleteModel(
            name='PublicationContextRelated',
        ),
    ]
