# Generated by Django 3.1.4 on 2021-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0006_auto_20210119_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicationattachment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicationblock',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicationcontext',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicationgallery',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicationlocalization',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicationrelated',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
