# Generated by Django 3.1.6 on 2021-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0012_alter_publication_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
