# Generated by Django 3.2.3 on 2021-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0016_auto_20210531_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Content'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Editorial Board notes'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='subheading',
            field=models.TextField(blank=True, default='', help_text='Strap line (press)', max_length=1024),
        ),
        migrations.AlterField(
            model_name='publicationattachment',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Specify the container section in the template where this block would be rendered.', max_length=60),
        ),
        migrations.AlterField(
            model_name='publicationlocalization',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Content'),
        ),
        migrations.AlterField(
            model_name='publicationlocalization',
            name='subheading',
            field=models.TextField(blank=True, default='', help_text='Strap line (press)', max_length=1024),
        ),
    ]
