# Generated by Django 3.2.5 on 2021-10-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0017_auto_20210614_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationcontext',
            options={'ordering': ['order'], 'verbose_name_plural': 'Publication Contexts'},
        ),
    ]
