# Generated by Django 3.2.5 on 2021-10-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0018_alter_publicationcontext_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationcontext',
            options={'ordering': ['webpath__fullpath', 'order'], 'verbose_name_plural': 'Publication Contexts'},
        ),
    ]
