# Generated by Django 3.2.5 on 2021-11-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0008_alter_media_file'),
        ('cmspublications', '0019_alter_publicationcontext_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='preview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preview_image', to='cmsmedias.media'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='presentation_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presentation_image', to='cmsmedias.media'),
        ),
    ]
