# Generated by Django 3.2.5 on 2021-12-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0020_auto_20211103_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationcontext',
            options={'ordering': ['webpath__fullpath', 'order', '-date_start'], 'verbose_name_plural': 'Publication Contexts'},
        ),
    ]
