# Generated by Django 3.2.5 on 2022-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0021_alter_publicationcontext_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationattachment',
            name='embedded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationlink',
            name='embedded',
            field=models.BooleanField(default=False),
        ),
    ]
