# Generated by Django 3.2.19 on 2023-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0022_auto_20220128_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationattachment',
            name='file_type',
            field=models.CharField(blank=True, choices=[('', '')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='publicationlocalization',
            name='language',
            field=models.CharField(choices=[('', '-')], default='en', max_length=12),
        ),
    ]
