# Generated by Django 3.1.6 on 2021-04-01 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmscarousels', '0003_auto_20210119_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitemlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carouselitemlink_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carouselitemlink',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carouselitemlink_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
