# Generated by Django 3.2.3 on 2021-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscarousels', '0005_auto_20210507_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='Heading', max_length=120),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='pre_heading',
            field=models.CharField(blank=True, default='', help_text='Pre Heading', max_length=120),
        ),
        migrations.AlterField(
            model_name='carouselitemlink',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title', max_length=120),
        ),
        migrations.AlterField(
            model_name='carouselitemlinklocalization',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title', max_length=120),
        ),
        migrations.AlterField(
            model_name='carouselitemlocalization',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carouselitemlocalization',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='Heading', max_length=120),
        ),
        migrations.AlterField(
            model_name='carouselitemlocalization',
            name='pre_heading',
            field=models.CharField(blank=True, default='', help_text='Pre Heading', max_length=120),
        ),
    ]
