# Generated by Django 3.2.5 on 2021-11-10 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0008_alter_media_file'),
        ('cmscarousels', '0006_auto_20210614_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='mobile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mobile_image', to='cmsmedias.media'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image', to='cmsmedias.media'),
        ),
    ]
