# Generated by Django 3.2.5 on 2022-04-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscarousels', '0007_auto_20211110_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitemlinklocalization',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
