# Generated by Django 3.2.5 on 2022-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscarousels', '0008_carouselitemlinklocalization_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitemlinklocalization',
            name='title',
            field=models.CharField(help_text='Title', max_length=120),
        ),
        migrations.AlterField(
            model_name='carouselitemlinklocalization',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
