# Generated by Django 3.2.5 on 2022-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscarousels', '0009_auto_20220428_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitemlinklocalization',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title', max_length=120),
        ),
    ]
