# Generated by Django 3.2.13 on 2022-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscarousels', '0010_alter_carouselitemlinklocalization_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
    ]
