# Generated by Django 3.2.13 on 2022-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscarousels', '0011_auto_20221219_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
