# Generated by Django 3.2.19 on 2023-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscarousels', '0012_auto_20221219_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitemlink',
            name='title_preset',
            field=models.CharField(choices=[('', '-')], default='custom', max_length=33),
        ),
        migrations.AlterField(
            model_name='carouselitemlinklocalization',
            name='language',
            field=models.CharField(choices=[('', '-')], default='en', max_length=12),
        ),
        migrations.AlterField(
            model_name='carouselitemlocalization',
            name='language',
            field=models.CharField(choices=[('', '-')], default='en', max_length=12),
        ),
    ]
