# Generated by Django 4.2.9 on 2024-07-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cmsmedias", "0013_alter_media_created_by_alter_media_modified_by_and_more"),
        (
            "cmscarousels",
            "0014_alter_carousel_created_by_alter_carousel_modified_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselitemlocalization",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localization_image",
                to="cmsmedias.media",
            ),
        ),
        migrations.AddField(
            model_name="carouselitemlocalization",
            name="mobile_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localization_mobile_image",
                to="cmsmedias.media",
            ),
        ),
    ]
