# Generated by Django 3.1.4 on 2021-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagetemplateblock',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='templateblock',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
