# Generated by Django 3.1.4 on 2021-01-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagetemplate',
            options={'managed': False, 'ordering': ['name'], 'verbose_name_plural': 'Page Templates'},
        ),
        migrations.AlterModelOptions(
            name='pagetemplateblock',
            options={'managed': False, 'verbose_name_plural': 'Page Template Blocks'},
        ),
        migrations.AlterModelOptions(
            name='templateblock',
            options={'managed': False, 'ordering': ['name'], 'verbose_name_plural': 'Template Blocks'},
        ),
    ]
