# Generated by Django 3.2.3 on 2021-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0003_auto_20210507_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('', 'No templates found')], max_length=1024),
        ),
    ]
