# Generated by Django 3.1.2 on 2020-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0003_auto_20201215_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('dipartimento_home_v3_dimes.html', 'dipartimento_home_v3_dimes.html'), ('publication_list.html', 'publication_list.html'), ('publication_view_hero_original.html', 'publication_view_hero_original.html'), ('italia.html', 'italia.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_dipartimento_v3.html', 'portale_home_dipartimento_v3.html'), ('portale_home_v_original.html', 'portale_home_v_original.html'), ('portale_home_dipartimento_v3_dimes.html', 'portale_home_dipartimento_v3_dimes.html'), ('unical_main_spaced_columns.html', 'unical_main_spaced_columns.html'), ('unical_main.html', 'unical_main.html'), ('dipartimento_home_v3.html', 'dipartimento_home_v3.html')], max_length=1024),
        ),
    ]
