# Generated by Django 3.1.4 on 2020-12-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0007_auto_20201228_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('dipartimento_home_v3_dimes.html', 'dipartimento_home_v3_dimes.html'), ('unical_main_center_alternative.html', 'unical_main_center_alternative.html'), ('publication_list.html', 'publication_list.html'), ('publication_view_hero_original.html', 'publication_view_hero_original.html'), ('italia.html', 'italia.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_dipartimento_v3.html', 'portale_home_dipartimento_v3.html'), ('portale_home_v_original.html', 'portale_home_v_original.html'), ('unical_right_spaced.html', 'unical_right_spaced.html'), ('portale_home_dipartimento_v3_dimes.html', 'portale_home_dipartimento_v3_dimes.html'), ('unical_center_top_ab_a_double.html', 'unical_center_top_ab_a_double.html'), ('unical_main.html', 'unical_main.html'), ('dipartimento_home_v3.html', 'dipartimento_home_v3.html')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='templateblock',
            name='type',
            field=models.TextField(choices=[('cms.templates.blocks.HtmlBlock', 'HTML Block'), ('cms.templates.blocks.JSONBlock', 'JSON Block'), ('cms.templates.blocks.CarouselPlaceholderBlock', 'Carousel Placeholder Block'), ('cms.templates.blocks.LinkPlaceholderBlock', 'Link Placeholder Block'), ('cms.templates.blocks.MenuPlaceholderBlock', 'Menu Placeholder Block'), ('cms.templates.blocks.PublicationContentPlaceholderBlock', 'Publication Content Placeholder Block')]),
        ),
    ]
