# Generated by Django 3.1.4 on 2020-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0009_auto_20201230_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateblock',
            name='type',
            field=models.TextField(choices=[('cms.templates.blocks.HtmlBlock', 'HTML Block'), ('cms.templates.blocks.JSONBlock', 'JSON Block'), ('cms.templates.blocks.CarouselPlaceholderBlock', 'Carousel Placeholder Block'), ('cms.templates.blocks.LinkPlaceholderBlock', 'Link Placeholder Block'), ('cms.templates.blocks.MediaPlaceholderBlock', 'Media Placeholder Block'), ('cms.templates.blocks.MenuPlaceholderBlock', 'Menu Placeholder Block'), ('cms.templates.blocks.PublicationContentPlaceholderBlock', 'Publication Content Placeholder Block')]),
        ),
    ]
