# Generated by Django 3.2.19 on 2023-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0012_alter_pagetemplate_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('', '-')], max_length=1024),
        ),
    ]
