# Generated by Django 3.1.4 on 2021-01-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0002_auto_20210114_1617'),
        ('cmstemplates', '0014_auto_20210112_0826'),
    ]

    operations = [
    ]
