# Generated by Django 3.1.4 on 2021-01-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0015_merge_20210114_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagetemplate',
            options={'ordering': ['name'], 'verbose_name_plural': 'Page Templates'},
        ),
        migrations.AlterModelOptions(
            name='pagetemplateblock',
            options={'verbose_name_plural': 'Page Template Blocks'},
        ),
        migrations.AlterModelOptions(
            name='templateblock',
            options={'ordering': ['name'], 'verbose_name_plural': 'Template Blocks'},
        ),
    ]
