# Generated by Django 3.2.17 on 2023-06-16 12:56
import django.contrib.admin.models
import django.db.models.deletion
import django.utils.timezone

from django.conf import settings
from django.contrib.admin.models import LogEntry
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models

from .. models import Log


def populate_custom_logs(apps, schema_editor):
    # models = ['ticket', 'task']
    unicms_contenttypes = ContentType.objects.filter(models.Q(app_label__startswith='cms') |
                                                     models.Q(app_label__startswith='unicms'))\
                                             .values_list('pk', flat=True)
    logs = LogEntry.objects.filter(content_type__pk__in=unicms_contenttypes)

    for (index, log) in enumerate(logs):
        Log.objects.create(
            user=log.user,
            content_type=log.content_type,
            object_id=log.object_id,
            object_repr=log.object_repr,
            action_flag=log.action_flag,
            change_message=log.change_message,
            action_time=log.action_time
        )
        print(f'n. {index} - {log}: OK')

    # logs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cmstemplates', '0015_log'),
    ]

    operations = [
        migrations.RunPython(populate_custom_logs),#, remove_old_logs),
    ]
