# Generated by Django 3.1.4 on 2021-01-14 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmstemplates', '0016_auto_20210114_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagetemplate_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagetemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagetemplate_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagetemplateblock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagetemplateblock_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagetemplateblock',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagetemplateblock_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateblock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templateblock_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateblock',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templateblock_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('dipartimento_home_v3_dimes.html', 'dipartimento_home_v3_dimes.html'), ('unical_main_center_alternative.html', 'unical_main_center_alternative.html'), ('publication_list.html', 'publication_list.html'), ('publication_view_hero_original.html', 'publication_view_hero_original.html'), ('italia.html', 'italia.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_dipartimento_v3.html', 'portale_home_dipartimento_v3.html'), ('portale_home_v_original.html', 'portale_home_v_original.html'), ('unical_right_spaced.html', 'unical_right_spaced.html'), ('portale_home_dipartimento_v3_dimes.html', 'portale_home_dipartimento_v3_dimes.html'), ('unical_center_top_ab_a_double.html', 'unical_center_top_ab_a_double.html'), ('unical_main.html', 'unical_main.html'), ('dipartimento_home_v3.html', 'dipartimento_home_v3.html')], max_length=1024),
        ),
    ]
