# Generated by Django 3.1.2 on 2020-12-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0003_auto_20201215_0928'),
        ('cmspages', '0002_auto_20201215_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.CreateModel(
            name='PagePublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_page', to='cmspages.page')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_content', to='cmspublications.publication')),
            ],
            options={
                'verbose_name_plural': 'Publication Contents',
            },
        ),
    ]
