# Generated by Django 3.1.4 on 2021-01-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspages', '0003_auto_20210119_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, help_text='Description used for SEO.', null=True),
        ),
    ]
