# Generated by Django 3.1.6 on 2021-04-01 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmspages', '0006_auto_20210314_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageblock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageblock_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageblock_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecarousel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagecarousel_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecarousel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagecarousel_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagelink_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagelink_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagemedia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagemedia_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagemedia',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagemedia_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagemenu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagemenu_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagemenu',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagemenu_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagerelated',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagerelated_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagerelated',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagerelated_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
