# Generated by Django 3.1.4 on 2020-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspages', '0007_pagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemedia',
            name='url',
            field=models.URLField(blank=True, help_text='url', null=True),
        ),
    ]
