# Generated by Django 3.1.6 on 2021-04-01 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmspages', '0007_auto_20210401_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepublication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagepublication_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagepublication',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagepublication_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
