# Generated by Django 3.2.19 on 2023-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspages', '0015_auto_20230112_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontact',
            name='section',
            field=models.CharField(blank=True, choices=[('', '-')], help_text='Specify the container section in the template where this block would be rendered.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pageheading',
            name='section',
            field=models.CharField(blank=True, choices=[('', '-')], help_text='Specify the container section in the template where this block would be rendered.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pageheadinglocalization',
            name='language',
            field=models.CharField(choices=[('', '-')], default='en', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagelocalization',
            name='language',
            field=models.CharField(choices=[('', '-')], default='en', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagemediacollection',
            name='section',
            field=models.CharField(blank=True, choices=[('', '-')], help_text='Specify the container section in the template where this block would be rendered.', max_length=60, null=True),
        ),
    ]
