# Generated by Django 3.1.4 on 2021-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0002_auto_20210115_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mediacollection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mediacollectionitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
