# Generated by Django 3.1.4 on 2021-01-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0003_auto_20201215_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Media'},
        ),
    ]
