# Generated by Django 3.1.6 on 2021-04-15 13:04

import cms.medias.models
import cms.medias.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0003_auto_20210119_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=cms.medias.models.context_media_path, validators=[cms.medias.validators.validate_media_file_extension, cms.medias.validators.validate_file_size, cms.medias.validators.validate_image_size_ratio]),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, choices=[('text/plain', 'text/plain'), ('application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.text'), ('application/msword', 'application/msword'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), ('text/csv', 'text/csv'), ('application/json', 'application/json'), ('application/vnd.ms-excel', 'application/vnd.ms-excel'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'), ('application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.spreadsheet'), ('application/wps-office.xls', 'application/wps-office.xls'), ('image/webp', 'image/webp'), ('image/jpeg', 'image/jpeg'), ('image/png', 'image/png'), ('image/gif', 'image/gif'), ('image/x-ms-bmp', 'image/x-ms-bmp'), ('video/mp4', 'video/mp4'), ('application/pdf', 'application/pdf'), ('application/pkcs7-mime', 'application/pkcs7-mime')], max_length=256, null=True),
        ),
    ]
