# Generated by Django 3.1.4 on 2021-01-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0004_auto_20210112_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='path',
            field=models.FilePathField(default=2020, match='*.*', path='/home/wert/DEV/uniCMS/uniCMS/example/media', recursive=True),
            preserve_default=False,
        ),
    ]
