# Generated by Django 3.1.6 on 2021-05-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0006_remove_media_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacollectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsmedias.mediacollection'),
        ),
        migrations.AlterField(
            model_name='mediacollectionitem',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmsmedias.media'),
        ),
    ]
