# Generated by Django 3.2.5 on 2022-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0008_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(help_text='Media file title', max_length=256),
        ),
    ]
