# Generated by Django 3.2.13 on 2022-12-19 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmedias', '0010_media_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
