# Generated by Django 3.1.4 on 2021-01-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmscontexts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoardLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('locked_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmscontexts_editorialboardlock_locked_items', to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name_plural': 'Editorial Board Locks',
                'ordering': ('-locked_time',),
            },
        ),
        migrations.CreateModel(
            name='EditorialBoardLockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmscontexts.editorialboardlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Editorial Board Locks Owners',
            },
        ),
        # migrations.DeleteModel(
            # name='EditorialBoardLocks',
        # ),
    ]
