# Generated by Django 3.1.4 on 2020-12-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0002_auto_20201227_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
