# Generated by Django 3.1.4 on 2021-01-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0003_auto_20210115_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditorialBoardLocks',
        ),
    ]
