# Generated by Django 3.1.4 on 2021-01-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0004_delete_editorialboardlocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardeditors',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
