# Generated by Django 3.1.4 on 2021-02-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0005_auto_20210120_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpath',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
