# Generated by Django 3.1.6 on 2021-05-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmscontexts', '0006_auto_20210204_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardeditors',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorialboardeditors_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='editorialboardeditors',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorialboardeditors_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webpath',
            name='alias',
            field=models.ForeignKey(blank=True, help_text='Alias that would be redirected to ...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_path', to='cmscontexts.webpath'),
        ),
        migrations.AlterField(
            model_name='webpath',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webpath_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webpath',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webpath_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
