# Generated by Django 3.1.4 on 2021-01-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0007_auto_20210109_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardeditors',
            name='permission',
            field=models.IntegerField(choices=[(1, 'can translate content in their own context'), (2, 'can translate content in their own context and descendants'), (3, 'can edit content created by them in their own context'), (4, 'can edit content in their own context'), (5, 'can edit content in their own context and descendants'), (6, 'can publish content created by them in their own context'), (7, 'can publish content in their own context'), (8, 'can publish content in their own context and descendants')], default=0),
        ),
    ]
