# Generated by Django 3.2.3 on 2021-06-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0007_auto_20210507_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpath',
            name='alias_url',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='webpath',
            name='fullpath',
            field=models.TextField(blank=True, default='', help_text='final path prefixed with the parent path', max_length=2048),
        ),
    ]
