# Generated by Django 3.1.4 on 2021-01-15 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cmscontexts', '0008_auto_20210109_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardeditors',
            name='permission',
            field=models.IntegerField(choices=[(0, 'no permissions in context'), (1, 'can translate content in their own context'), (2, 'can translate content in their own context and descendants'), (3, 'can edit content created by them in their own context'), (4, 'can edit content in their own context'), (5, 'can edit content in their own context and descendants'), (6, 'can publish content created by them in their own context'), (7, 'can publish content in their own context'), (8, 'can publish content in their own context and descendants')], default=0),
        ),
        migrations.CreateModel(
            name='EntryUsedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('usedby_object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmscontexts_entryusedby_entry', to='contenttypes.contenttype', verbose_name='content type')),
                ('usedby_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmscontexts_entryusedby_usedby', to='contenttypes.contenttype', verbose_name='content type')),
            ],
        ),
    ]
