# Generated by Django 3.2.5 on 2021-10-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0008_auto_20210614_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpath',
            options={'ordering': ['name'], 'verbose_name_plural': 'Site Contexts (WebPaths)'},
        ),
    ]
