# Generated by Django 3.1.4 on 2021-01-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cmscontexts', '0009_auto_20210115_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryusedby',
            old_name='usedby_object_id',
            new_name='used_by_object_id',
        ),
        migrations.RemoveField(
            model_name='entryusedby',
            name='usedby_content_type',
        ),
        migrations.AddField(
            model_name='entryusedby',
            name='used_by_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cmscontexts_entryusedby_usedby', to='contenttypes.contenttype', verbose_name='used by content type'),
            preserve_default=False,
        ),
    ]
