# Generated by Django 3.1.4 on 2021-01-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0010_auto_20210115_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryusedby',
            options={'verbose_name_plural': 'Entries Used By'},
        ),
    ]
