# Generated by Django 3.2.5 on 2021-10-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0010_alter_webpath_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpath',
            options={'ordering': ['fullpath'], 'verbose_name_plural': 'Site Contexts (WebPaths)'},
        ),
    ]
