# Generated by Django 3.2.13 on 2022-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0011_alter_webpath_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpath',
            name='robots',
            field=models.CharField(choices=[('index, follow', 'index, follow'), ('noindex, follow', 'noindex, follow'), ('index, nofollow', 'index, nofollow'), ('noindex, nofollow', 'noindex, nofollow')], default='index, follow', max_length=20),
        ),
    ]
