# Generated by Django 3.2.13 on 2022-06-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0012_webpath_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpath',
            name='meta_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webpath',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
