# Generated by Django 3.2.19 on 2023-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0014_website_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardeditors',
            name='permission',
            field=models.IntegerField(choices=[(0, '-')], default=0),
        ),
        migrations.AlterField(
            model_name='webpath',
            name='robots',
            field=models.CharField(choices=[('', '-')], default='index, follow', max_length=20),
        ),
    ]
