# Generated by Django 4.2.9 on 2024-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmscontexts", "0016_alter_editorialboardeditors_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpath",
            name="access",
            field=models.CharField(choices=[("", "-")], default="1", max_length=50),
        ),
    ]
