# Generated by Django 4.2.9 on 2024-05-08 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cmscontexts", "0017_webpath_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialboardlockuser",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
